markdown: kramdown
highlighter: rouge

permalink: /posts/:title.html
excerpt_separator: "<!-- TOC -->"
#excerpt_separator: "<!-- more -->"

github: xdaping
author: "xdaping"
email: xdaping#163.com
name: "xdaping-github博客"
url: http://xdaping.github.io
domain: xdaping.github.io
all_categories: [
["links", "常用链接", "/posts/links.html"],
["knowledge", "基础知识", "/posts/knowledge.html"],
["programme", "编程语言", "/posts/programme.html"],
["platform", "常用平台", "/posts/platform.html"],
["ml", "机器学习","/posts/ml.html"], 
["dl", "深度学习","/posts/dl.html"],
["rl", "强化学习","/posts/rl.html"],
["cv", "图像处理","/posts/cv.html"], 
["nlp", "自然语言处理","/posts/nlp.html"], 
["other", "其他","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 10
paginate_path: "posts/page:num"
timezone: China/Beijing

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
 - jekyll-toc


